docs/_data/members/bill_westfall.yaml
=> belt request

docs/_data/members/jeremy_mcmillan.yaml
=> Jeremy McMillan white belt request

docs/_config.yml, docs/_data/domains/Mindset.yaml
Was a key part of Agile training and great new Systems Thinking Lens
=> feat: Uplift Tagline and Mindset

docs/_data/domains/Mindset.yaml
Distilling further influenced by some time pressure from upcoming presentation to Cloud Security Office Hours.
Looking for commentary at this point, once everyone has had a reasonable chance to weigh in then can move for approval.
=> feat: Uplift Mindset Principles

docs/_data/domains/Mindset.yaml
Proposing this introduction to the Systems Thinking model for Cynefin.
It is simpler and clearer how it compliments other models like Agile.
Should be easier to digest.
=> refactor: Simpler Cynefin introduction

docs/_data/domains/Mindset.yaml
After doing some deep mindset work this past weekend this adjustment came to surface.
@abkaufmann @billwestfall @aphor @jimmanzzullo @nbasil - please feel free to comment.
However, do not approve or merge.  
I would like to make sure to get a chance to see how this (proposed change idea) resonates or not with @anuolu.
Warmly.
Michael Basil 🌿
=> refactor: Mindset Mission Wholeheartedness

docs/_data/domains/Mindset.yaml
Based on reflection of mission and principles of Mindset this moves forward the curriculum in a more relevant way.
=> feat: Update Mindset Movie

docs/_config.yml
Smoothing out some concepts and to set the tone for those who will happen into a Dojo Circle
**People-First Insightful Learning Circles ("Third Places")**
Within our peer-supported community circles, we engage in Insightful Learning and realize Metashifts—pivotal transformations in mindset, metaphor, modality and motivation. As we unpack conversations, phases of Compassionate Conflict may emerge periodically like a healthy rain. This is one of the key Metashifts to transition from fear-based approaches to open, wholehearted connection, akin to sports, dance or music rather than combat. This approach unleashes greater potential for creative flow, empowering you to become a Self-Author.
=> refactor: Pitch

docs/_data/domains/Mindset.yaml
The proposed video grounds Mindset into Theory of Constraints which is at the base and heart of Lean, Agile and Systems Thinking in general.
The illustration and metaphor is relevant today when we think about cost cutting.  What happens when we no longer have the straws in our systems?
=> refactor: Theory of Constraints into Mindset Green

docs/Belt-Request.md, docs/_data/domains/Mindset.yaml
Bias towards synchronous communication and follow conventions with existing communities in Slack, etc.
=> refactor: Mindset Belt Claim Process

docs/_data/domains/Mindset.yaml
@anuolu @jimmanzzullo @billwestfall ... thought you may be good to review this article to see if it resonates enough to be considered for Mindset Red.
=> feat: Add 4th-Person Knowing (Circles) article

docs/_data/domains/Mindset.yaml
This article introduces Spiral Dynamics in a way which can suggest how to refer back to it during tricky situations like confusing conflicts.
It also ties in nicely with popular psychology knowledge like Maslow and gives a point of further exploration if people dig into the author and their self-actualization free guides.
=> feat(Mindset): Add Self Actualization exercises to red level

docs/Orientation-Request.md
This was discussed at the Dojo Circle on July 12th.
The main ideas are to:
* Help the reader connect with their own why
* Center on the Mission and Principles of the domain
* Facilitate as an introduction for them into the Circle Community
=> feat: Add White Level reflection

docs/_data/domains/Mindset.yaml
Video describing a mindset experience with Miles Davis
=> Add Miles Davis mindset video

docs/_data/domains/Mindset.yaml
Make a clear shift designation with regards to Be-Do-Have versus Have-Do-Be
Open to conversation on this via the pull request from @billwestfall  @jimmanzzullo @abkaufmann @anuolu @nbasil @fzuill @aphor 
Candidate discussion for Friday's call
🌿
=> feat: Uplift Mindset Mission - Be-Do-Have / Abundance

docs/_data/domains/Mindset.yaml
More purposeful and open minded to allow people to Self-determine.
=> feat: Uplift Mindset

docs/_data/domains/Mindset.yaml
Doing some final preps before I draft my black belt claim reflection
Black level is embodiment so what I am thinking is that the reflection will have to demonstrate how each of the principles work together and show through story how they have permeated positively and productively into multiple life realms.
=> feat: Uplift Mindset Emotional Mastery

docs/_data/domains/Mindset.yaml
More engaging and clearer.   Should prompt good conversation.
=> feat: Uplift Spiral Dynamics

docs/_data/members/michael-basil.yaml
In the garden of life, each of us tends to our own plot, nurturing the seeds of potential we've planted. My journey to claim the red belt in Mindset Dojo has been akin to cultivating a new section of this garden—planting principles and practices meant to help me thrive.
With each principle—reconnecting with purpose under pressure, intelligent conflict, emotional flow, and intentional repetition—I planted seeds in the soil of my mind. These principles became the foundation of my growth, each representing a vital element necessary for development.
At first, like learning to ride a bicycle, I stumbled, unsure of how to balance these new ideas in the practical world. But with each fall, I gained a deeper understanding, learning the patience and resilience needed for true growth.
Leading …
=> belt request - Michael Basil - Mindset Red Level

docs/_data/domains/Mindset.yaml
Per discussion with @abkaufmann and self-reflection
=> feat: Uplift Mindset Mission
